DROP DATABASE IF EXISTS six_new_users;
CREATE DATABASE IF NOT EXISTS six_new_users;
USE six_new_users;

-- Create admin_001
DROP USER IF EXISTS 'admin_001'@'%';
CREATE USER 'admin_001'@'%'
IDENTIFIED BY 'guttmanGrizzlies_2024'
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME UNBOUNDED
PASSWORD EXPIRE INTERVAL 90 DAY
PASSWORD HISTORY 5
PASSWORD REUSE INTERVAL 365 DAY;

REVOKE ALL, GRANT OPTION FROM 'admin_001'@'%';
GRANT SELECT ON classicmodels.* TO 'admin_001'@'%';

-- Create admin_002
DROP USER IF EXISTS 'admin_002'@'%';
CREATE USER 'admin_002'@'%'
IDENTIFIED BY 'guttmanGrizzlies_2024'
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME UNBOUNDED
PASSWORD EXPIRE INTERVAL 90 DAY
PASSWORD HISTORY 5
PASSWORD REUSE INTERVAL 365 DAY;

REVOKE ALL, GRANT OPTION FROM 'admin_002'@'%';
GRANT SELECT ON classicmodels.* TO 'admin_002'@'%';

-- Create admin_003
DROP USER IF EXISTS 'admin_003'@'%';
CREATE USER 'admin_003'@'%'
IDENTIFIED BY 'guttmanGrizzlies_2024'
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME UNBOUNDED
PASSWORD EXPIRE INTERVAL 90 DAY
PASSWORD HISTORY 5
PASSWORD REUSE INTERVAL 365 DAY;

REVOKE ALL, GRANT OPTION FROM 'admin_003'@'%';
GRANT SELECT ON classicmodels.* TO 'admin_003'@'%';

-- create admin_004
DROP USER IF EXISTS 'admin_004'@'%';
CREATE USER 'admin_004'@'%'
IDENTIFIED BY 'guttmanGrizzlies_2024'
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME UNBOUNDED
PASSWORD EXPIRE INTERVAL 90 DAY
PASSWORD HISTORY 5
PASSWORD REUSE INTERVAL 365 DAY;

REVOKE ALL, GRANT OPTION FROM 'admin_004'@'%';
GRANT SELECT ON classicmodels.* TO 'admin_004'@'%';

-- create admin_005
DROP USER IF EXISTS 'admin_005'@'%';
CREATE USER 'admin_005'@'%'
IDENTIFIED BY 'guttmanGrizzlies_2024'
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME UNBOUNDED
PASSWORD EXPIRE INTERVAL 90 DAY
PASSWORD HISTORY 5
PASSWORD REUSE INTERVAL 365 DAY;

REVOKE ALL, GRANT OPTION FROM 'admin_005'@'%';
GRANT SELECT ON classicmodels.* TO 'admin_005'@'%';

-- create admin_006
DROP USER IF EXISTS 'admin_006'@'%';
CREATE USER 'admin_006'@'%'
IDENTIFIED BY 'guttmanGrizzlies_2024'
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LOCK_TIME UNBOUNDED
PASSWORD EXPIRE INTERVAL 90 DAY
PASSWORD HISTORY 5
PASSWORD REUSE INTERVAL 365 DAY;

REVOKE ALL, GRANT OPTION FROM 'admin_006'@'%';
GRANT SELECT ON classicmodels.* TO 'admin_006'@'%';

FLUSH PRIVILEGES;

/*
-- create roles

-- create read_only_classicmodels_db role
CREATE ROLE read_only_classicmodels_db;

-- create admin_user role
CREATE ROLE admin_user;

-- create read_only_employees_db role
CREATE ROLE read_only_employees_db;

-- create app_user role
CREATE ROLE app_user;


FLUSH PRIVILEGES;

-- note

FLUSH PRIVILEGES;

-- note

FLUSH PRIVILEGES;

*/
-- very last line
FLUSH PRIVILEGES;
